### ISSUE TITLE
Uploaded code is not reproducable.

### ISSUE THREAD

**Issue by deepneuralnetworks** [facebookresearch/ExPLORe#3]
Hello, thank you for the awesome work. 

I tried to reproduce your work but I can't import 'filter_antmaze' because it is not exist.

Also, many method names are different from [https://github.com/ikostrikov/rlpd.git](url).
Example, 'get_iter' in your work is 'get_iterator', and some arguments are missing and don't fit, especially in the replay_buffer.

I think there are many modification in [https://github.com/ikostrikov/rlpd.git](url) for your work.

Could you upload the rlpd/data folder that you used in the research?

Thank you for reading my issue.

**Comment by ColinQiyangLi** [comment]
Sorry for the inconvenience! I forgot to upload the `rlpd/data` in the initial release. This [PR](https://github.com/facebookresearch/ExPLORe/pull/4) (merged) should fix it. Thank you for your interest in our work and please let us know if you run into other issues reproducing our work!!

**Comment by deepneuralnetworks** [comment]
Thank you for the kind and fast reply.
I read your paper impressively. I can't wait to try it. 
Again thank you for the awesome work!

**Comment by deepneuralnetworks** [comment]
Hello. I'm trying to reproduce the COG part now but found ModuleNotFoundError like below.

`ModuleNotFoundError: No module named 'rlpd.data.cog_datasets'`

Could you please upload the missing code please?

Thank you for reading my issue.

**Comment by deepneuralnetworks** [comment]
Hello. I'm trying to reproduce the COG part now but found error like below.

`FileNotFoundError: [Errno 2] No such file or directory: 'data/pickplace/successful/prior_success.npy'`

None of success.npy files are in the given google drive URL (https://drive.google.com/drive/folders/1jxBQE1adsFT1sWsfatbhiZG6Zkf3EW0Q)

Could you please upload the missing file please?

If the data in success.npy are handpicked from the prior and task dataset in google drive, can you please let me know how to extract it?

Thank you for reading my issue.

!! UPDATED !!
I'm using the success.npy with the conditions as follows:
Each of the data is extracted from the corresponding files in google drive.

block1drawer
prior: If **'opened', 'top_closed'** in 'env_infos' is **True** at the **last step**
task: If **'grasp', 'opened', 'top_closed'** in 'env_infos' is **True** at the **last step**

closeddrawer
prior: If **'opened', 'top_closed'** in 'env_infos' is **True** at the **last step**
task: If **'grasp', 'opened', 'top_closed'** in 'env_infos' is **True** at the **last step**

pickplace
prior: If **'grasp_success'** in 'env_infos' is **True** at the **last step**
task: If **'place_success'** in 'env_infos' is **True** at the **last step**

Is my way to extract the success.npy is same as yours?

I've attached code snippet used for extraction below.
Thank you for reading my issue again.

```# Load COG Dataset
data = np.load('./pickplace_task.npy', allow_pickle=True)

# Extract the successful trajectory
s = []
for dt in data:
    elem = dt['env_infos'][-1]
    success = elem['place_success']
    if success:
        s.append(dt)

# Change list -> array
s = np.array(s)

# Save files
np.save('task_success.npy', s, allow_pickle=True)

**Comment by jazhang00** [comment]
Hi, thanks for letting us know about this! I believe the procedure you described to extract the successful trajectories is also correct, but in case there are discrepancies, the data used for our COG experiments can be found at this Dropbox [link](https://www.dropbox.com/scl/fo/ve5ilhpftl8rozpw0vk3a/AOFjaxI3EhE6cralOK0q_Uo?rlkey=mxbb2haimo7vkpvxjpfzv0tu4&st=6gguyw6b&dl=0). The link contains a `data.zip` file containing the successful trajectories as well as sub-sampled prior and task data. We will also update the README to reflect this shortly.

**Comment by deepneuralnetworks** [comment]
Hello, Dr. Zhang. Thank you for the response and careful consideration of my question. I've download the dataset through the link and started reproducing the experiment. Again thank you for the great work!
